---
title: "Tic Tac Toe Notes"
output: github_notebook
editor_options: 
  chunk_output_type: console
---

## Notes

- R error and warning handling is canonically through `tryCatch`, see https://advanced-r-solutions.rbind.io/conditions.html#signalling-conditions, http://mazamascience.com/WorkingWithData/?p=912,  https://stackoverflow.com/questions/8093914/use-trycatch-skip-to-next-value-of-loop-upon-error , 

- Lists in R *are * ordered, even though they can also be named - good writeup: https://stackoverflow.com/questions/2050790/how-to-correctly-use-lists-in-r 
- R base set operations are set up to work on vectors
- Trying to create a tibble from vectors like this does not work and only reads the first vector: `as_tibble(c(1,2,3), c(4,5,6), c(7,8,9), c(1,4,7), c(2,5,8), c(3,6,9), c(1,5,9), c(3,5,7))`
- sapply is a simplified version of lapply output (lapply returns a list same length as original element)

- Can use combinat::permn to generate all permutations of a vector
- Can use `purrr::map2()` to operate on 2 things eg "(data = DATA FOR ONE SPECIES, n = SAMPLE SIZE)", per https://jennybc.github.io/purrr-tutorial/ls12_different-sized-samples.html

- Taking in input from the prompt is not a functionality I had used before in R, but it definately exists (see eg packages built to provide in-IDE tutorials from an R package such as `swirl`)
  - https://www.datamentor.io/r-programming/examples/user-input/
  - https://stackoverflow.com/questions/33425727/calling-user-inputs-prompted-through-one-r-function-in-a-second-r-function 

- Existing R package (haven't looked at the code) https://github.com/kota7/tictactoe 

## Steps and desired features

- Two humans play against each other
- A message when the function is first called: eg  "Welcome to tic tac toe! This is a game for two players. The goal is to get three x's or o's in a row!

You can take turns entering your move in this window. There are a total of 9 positions on the board, as show below: 
" - Done
- Optional - flip a coin to decide who goes first

- Initialize sets to store moves from each player - Done

- A new message that shows the state of the board and promps one player to enter their move (from 1 to 9) - Done

- The number the first player enters is added to their set of moves - Done

- State of board is updated, and the second player is prompted to enter their move - Done

- Loop three steps above, evaluating win conditions at each iteration
    - There are 8 possible configurations for each player to win, which are easy to list as a set (order doesn't matter)
    
- Can identify and report when situation is a tie

### Tic tac toe and dealing with user input in other languages
- https://towardsdatascience.com/tic-tac-toe-creating-unbeatable-ai-with-minimax-algorithm-8af9e52c1e7d
- https://stackoverflow.com/questions/23294658/asking-the-user-for-input-until-they-give-a-valid-response

